### ISSUE TITLE
 weird error 127,  weird error 127

### ISSUE THREAD

**Issue by dhingratul** [mlajtos/moniel#15]
> moniel@0.0.1 start /home/dhingratul/moniel
> ./node_modules/.bin/electron .

sh: 1: ./node_modules/.bin/electron: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by mlajtos** [comment]
Have you done ```npm install``` before? Also, what version is your NPM (```npm --version```)?

**Comment by dhingratul** [comment]
No, haven't installed it before, npm version 1.3.10

**Comment by mlajtos** [comment]
You have to do ```npm install``` before ```npm start```.

I don't have access to the version of NPM you have, so I cannot reproduce the error. Please consider an upgrade of NPM. Your version is almost 4 years old.

**Comment by dhingratul** [comment]
I haven't used npm before, and I did use npm install to install npm, and it installed this version by default. If you can let me know what stable version you have tested on, i can search for that and install it.

**Comment by mlajtos** [comment]
By running ```npm install``` you install necessary packages for this project. Can you please post output of running that command?

You can update NPM by running this command: ```npm install npm@latest -g```. Latest version is 5.3.0. The oldest version I got on my system was NPM 2.15.1 (Node 0.10.48) and it ran OK with it.

**Comment by dhingratul** [comment]
I will try to use the version you had. For you reference, this is the error when running npm install

dhingratul@dhingratul-Vostro-3458:~/moniel$ npm install 
npm http GET https://registry.npmjs.org/color-hash
npm http GET https://registry.npmjs.org/dagre
npm http GET https://registry.npmjs.org/electron-devtools-installer
npm http GET https://registry.npmjs.org/d3
npm http GET https://registry.npmjs.org/graphlib
npm http GET https://registry.npmjs.org/jquery
npm http GET https://registry.npmjs.org/ohm-js
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/react
npm http GET https://registry.npmjs.org/react-dom
npm http GET https://registry.npmjs.org/string-pixel-width
npm http GET https://registry.npmjs.org/babel-cli
npm http GET https://registry.npmjs.org/babel-plugin-transform-class-properties
npm http GET https://registry.npmjs.org/babel-plugin-transform-object-rest-spread
npm http GET https://registry.npmjs.org/babel-preset-es2017
npm http GET https://registry.npmjs.org/babel-preset-latest
npm http GET https://registry.npmjs.org/babel-preset-react
npm http GET https://registry.npmjs.org/electron
npm http GET https://registry.npmjs.org/electron-packager
npm http GET https://registry.npmjs.org/ace-moniel-builds
npm http GET https://registry.npmjs.org/fira-code
npm http GET https://registry.npmjs.org/electron-reload
npm http GET https://registry.npmjs.org/node-sass
npm http 304 https://registry.npmjs.org/d3
npm http 304 https://registry.npmjs.org/electron-devtools-installer
npm http 304 https://registry.npmjs.org/graphlib
npm http 304 https://registry.npmjs.org/color-hash
npm http 304 https://registry.npmjs.org/jquery
npm http 304 https://registry.npmjs.org/dagre
npm http 200 https://registry.npmjs.org/react-dom
npm http 200 https://registry.npmjs.org/react
npm http 200 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/babel-plugin-transform-object-rest-spread
npm http 304 https://registry.npmjs.org/babel-plugin-transform-class-properties
npm http 304 https://registry.npmjs.org/string-pixel-width
npm http 304 https://registry.npmjs.org/babel-preset-es2017
npm WARN deprecated babel-preset-es2017@6.24.1: We're really excited that you're trying to use ES2017 syntax, but instead of making more yearly presets, Babel has a better preset that we recommend you use instead: npm install babel-preset-env --save-dev. Give us a follow @babeljs to get more updates
npm http 304 https://registry.npmjs.org/ohm-js
npm http 304 https://registry.npmjs.org/babel-preset-react
npm http 404 https://registry.npmjs.org/ace-moniel-builds
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-93-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/dhingratul/moniel
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm http 304 https://registry.npmjs.org/electron
npm http 200 https://registry.npmjs.org/electron-packager
npm http 304 https://registry.npmjs.org/electron-reload
npm http 304 https://registry.npmjs.org/babel-cli
npm http 304 https://registry.npmjs.org/babel-preset-latest
npm WARN deprecated babel-preset-latest@6.24.1: 💥  preset-latest accomplishes the same task as babel-preset-env. 🙏  Please install it with 'npm install babel-preset-env --save-dev'. '{ "presets": ["latest"] }' to '{ "presets": ["env"] }'. For more info, please check the docs: http://babeljs.io/docs/plugins/preset-env 👌. And let us know how you're liking Babel at @babeljs on 🐦 
npm http 404 https://registry.npmjs.org/fira-code
npm ERR! TypeError: Object.keys called on non-object
npm ERR!     at Function.keys (native)
npm ERR!     at installTargetsError (/usr/share/npm/lib/cache.js:708:24)
npm ERR!     at /usr/share/npm/lib/cache.js:638:10
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:142:7)
npm ERR!     at /usr/lib/nodejs/graceful-fs/polyfills.js:133:7
npm ERR!     at Object.oncomplete (fs.js:107:15)
npm ERR! If you need help, you may report this log at:
npm ERR!     <http://github.com/isaacs/npm/issues>
npm ERR! or email it to:
npm ERR!     <npm-@googlegroups.com>

npm ERR! System Linux 4.4.0-93-generic
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install"
npm ERR! cwd /home/dhingratul/moniel
npm ERR! node -v v0.10.25
npm ERR! npm -v 1.3.10
npm ERR! type called_on_non_object
npm http 200 https://registry.npmjs.org/node-sass
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/dhingratul/moniel/npm-debug.log
npm ERR! not ok code 0
dhingratul@dhingratul-Vostro-3458:~/moniel$ npm start

> moniel@0.0.1 start /home/dhingratul/moniel
> ./node_modules/.bin/electron .

sh: 1: ./node_modules/.bin/electron: not found
npm ERR! weird error 127
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! not ok code 0

**Comment by mlajtos** [comment]
This seems to be the same problem as you have: https://github.com/mlajtos/moniel/issues/10

**Comment by mlajtos** [comment]
Reason for this error is definitely the old NPM.

**Comment by dhingratul** [comment]
ok, thanks.

**Comment by mlajtos** [comment]
Have you solved it?

**Comment by dhingratul** [comment]
No, it still installs 1.3.10 by npm install npm@latest -g

**Comment by mlajtos** [comment]
How about ```sudo npm install npm@latest -g```?

**Comment by dhingratul** [comment]
No

/usr/local/lib/node_modules/npm/lib/config/cmd-list.js:113
module.exports.aliases = Object.assign({}, shorthands, affordances)
                                ^
TypeError: Object function Object() { [native code] } has no method 'assign'
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/config/cmd-list.js:113:33)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /usr/local/lib/node_modules/npm/lib/npm.js:37:17
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/lib/npm.js:471:3)
    at Module._compile (module.js:456:26)

**Comment by mlajtos** [comment]
This might be a way for you:
1. Install package named ```n```:
```
sudo npm install -g n
```
2. Use it to install latest nodejs
```
sudo n latest
```

**Comment by dhingratul** [comment]
[2017-09-04T21_43_42_285Z-debug.log.zip](https://github.com/mlajtos/moniel/files/1275554/2017-09-04T21_43_42_285Z-debug.log.zip)
I am using an alternate machine, ubuntu 16.04LTS. 
npm --version 5.4.0
error 
npm ERR! Buffer.alloc is not a function

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dhingratul/.npm/_logs/2017-09-04T21_43_42_285Z-debug.log

**Comment by mlajtos** [comment]
@dhingratul I am sorry I could not help you with this issue. But at least it made me realize that a tool that runs in the browser (without any setup) is always better. And so, I honored this approach in my new thing – [L1: Tensor Studio](https://github.com/mlajtos/L1). Thank you for this lesson. :)
