### ISSUE TITLE
Ability to export as vector image

### ISSUE THREAD

**Issue by bstemper** [mlajtos/moniel#16]
I have not found an option to export the graph as a vector image which would be a very handy tool.

**Comment by mlajtos** [comment]
Hi Ben, try Menu -> Sketch -> Save (Ctrl+S on Win or Cmd-S on Mac).It will generate SVG file (along other stuff) in "sketches" folder.

Edit: If this approach is not intuitive, please suggest how it would be better. Thanks :)
