### ISSUE TITLE
Improvement ideas

### ISSUE THREAD

**Issue by otaj** [mlajtos/moniel#19]
Hi,

I started using moniel and have couple improvement ideas ;)

- Configuration options - in which you could set couple important options, like
  - Color palette of the nodes
  - Whether to draw Input/Output nodes of each Block (clutters workspace too much)
  - What text labels to include (It might be nice to have written in the node of for example Convolution its params such as kernel size and stride)
  - Optionally require mode with dimensions, where the graph would check, whether the dimension of input blocks check (you cannot add two tensors of a different dimension)
- Continuous saving.
- Choosing what (no need for print screen most of the time for example) and where to save

**Comment by mlajtos** [comment]
Hello :)

1. **Color palette** – There are at least two ways how to achieve this quite easily. One is to alter the [ColorHash](https://github.com/mlajtos/moniel/blob/master/src/scripts/ColorHash.js) class so it generates different set of colors. Or the second one is to override the color on each node by some param (```Convolution(color=red)```) First one is more straightforward, and the second is more flexible – but I don't know what you want to accomplish.

2. **I/O nodes** – Yes. They should be smaller at least. It would be difficult to layout the graph without them. Example: ```In -> [A, B] -> Out```

3. **Text labels** – Can you mock up a picture of how it would look like?

4. **Dimension check** – This is beyond the scope of this project. But I have something different up my sleeve...

5. **Saving** – Continuous saving would be really cool. Selecting save location would be nice. By "print screen" you mean PDF generation? Yes that is probably useless; having just SVG is probably ok.
