### ISSUE TITLE
Split into custom layers

### ISSUE THREAD

**Issue by alejandrojapkin** [mlajtos/moniel#20]
Is it possible to create split custom layer-wise layers?  like so:
<img width="734" alt="screen shot 2018-05-23 at 12 33 40" src="https://user-images.githubusercontent.com/5109806/40434881-c15cb70c-5e85-11e8-80ce-e3d3902c9e0c.png">

**Comment by mlajtos** [comment]
![screenshot 2018-05-24 19 51 20](https://user-images.githubusercontent.com/1047512/40502654-e9ab914a-5f8b-11e8-9d67-9023cfa15e14.png)

```
+Block {
    In -> [a:Ten, b:Ten]
    [a,b] -> Ten -> x:Ten -> Out
    b -> x
}

B -> B -> B
```

`¯\_(ツ)_/¯`
