### ISSUE TITLE
This is great - is development being continued?

### ISSUE THREAD

**Issue by shamoons** [mlajtos/moniel#24]

**Comment by mlajtos** [comment]
I haven’t touched it for quite some time. What is your usecase and what features are you missing?

**Comment by shamoons** [comment]
I’d like to display the kernel size, stride, etc in the diagram.

**Comment by mlajtos** [comment]
Something like this?

<img width="550" alt="Snímka obrazovky 2020-04-11 o 20 59 40" src="https://user-images.githubusercontent.com/1047512/79052527-66534480-7c37-11ea-993a-a83fb544e3e2.png">

**Comment by shamoons** [comment]
Yup! That’s it! Thank you!
