### ISSUE TITLE
Multiple inputs and outputs (for RNNs)

### ISSUE THREAD

**Issue by spro** [mlajtos/moniel#7]
Is there a way to represent multiple inputs and outputs for a single block? E.g. if I have a "input" and "prev_hidden" for a RNN module. The following is my best guess, but isn't right:

```
+RecurrentNeuralNetwork {
    in: Input
    prev_hidden: Input
    out: Output
    next_hidden: Output
    [in, prev_hidden] -> combine:Linear -> [out, next_hidden]
}

[in:Input, prev_hidden:Input] -> rnn1:RNN -> rnn2:RNN
```

![](https://i.imgur.com/MSqyVCb.png)

**Comment by mlajtos** [comment]
So you wanted to create something similar to this?

![screenshot 2017-02-21 01 19 58](https://cloud.githubusercontent.com/assets/1047512/23146181/c8b8829c-f7d4-11e6-941e-588f3fcb6ca5.png)

But these kind of diagrams are better when they are sideways:
![screenshot 2017-02-21 01 56 34](https://cloud.githubusercontent.com/assets/1047512/23146667/1d45cd0c-f7d9-11e6-8a77-2b1138ff9309.png)

**Comment by mlajtos** [comment]
These kind of diagrams are better when they are sideways:
![screenshot 2017-02-21 01 56 34](https://cloud.githubusercontent.com/assets/1047512/23146667/1d45cd0c-f7d9-11e6-8a77-2b1138ff9309.png)

**Comment by spro** [comment]
Yes, exactly that.

**Comment by spro** [comment]
By the way, how do you change it to horizontal?

**Comment by mlajtos** [comment]
0.) git pull
~~1.) View -> Toggle Developer Tools~~
~~2.) localStorage.setItem(“layout”, “rows”);~~
~~3.) View -> Reload~~
1.) 
![screenshot 2017-03-26 22 46 05](https://cloud.githubusercontent.com/assets/1047512/24335029/161d5e8e-1276-11e7-9d25-d42884f2351a.png)
