### ISSUE TITLE
Menu bar not working Windows 10-x64

### ISSUE THREAD

**Issue by laur1s** [mlajtos/moniel#9]
I am using Windows 10 and it seems that nothing is working right except the editing and model display. I can't even save my model 
I got this command after running npm install
> `
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})`

**Comment by mlajtos** [comment]
That log message is not an issue. This project is in a very early stage and is basically a throwaway prototype that survived. I add/remove stuff as I need it along the way - it's an active exploration.

I added saving, so it should kinda work. Do you have the latest commit? I added first steps towards saving - for now it saves only PDF of what you can see, a screenshot basically. Tomorrow I will add saving of the source as simple text file. Press Ctrl+S and look for "sketches" directory in the repo. Maybe it won't work if the "sketches" direcory is not present... I'll look into it in the morning.

Opening is not a priority for me right now. Changing the direction of the layout should definitely be in the menubar and not burried in the console, though.

**Comment by mlajtos** [comment]
It should be much better now. Hope you'll like it.

**Comment by mlajtos** [comment]
Oh, BTW I don't have any Windows machine, so I couldn't reproduce your issue. :(

**Comment by laur1s** [comment]
Happy to report, that saving the file works now, it saves pdf, json, and txt files. Great project overall, I hope you keep it up!

**Comment by mlajtos** [comment]
Glad to hear that! :) I will but the tempo could be better..
